### ISSUE TITLE
[Bug]: No symbols found

### ISSUE THREAD

**Issue by Shtoyan** [EliotVU/UnrealScript-Language-Service#157] opened 2023-01-30 11:35 UTC
### Describe the bug

After 0.6.0 symbols started to appear in `Outline` tab. But they behave quite strangely:

- For some classes they just work fine and instantly.
- For others it will warn you `no symbols found in document` and show nothing. It doesn't depend on a file size - huge hud files can work and small utility classes will bug out.

You can fix it by editing-saving the file or switching to other classes several times.

### Screenshots

Not a screenshot but a short video demonstration: https://youtu.be/h22MRGMKCwI

**Comment by Shtoyan** [comment] 2023-01-30 11:41
And a little post scriptum: seems like extension parses the document for symbols on each file switch / reopen. Maybe change it, so it triggers only on file modification?

**Comment by EliotVU** [comment] 2023-01-30 23:37
This could definitely be done better, but basically VSCode is waiting for the server to respond as it is still indexing all the dependencies, which is why it's sometimes not showing up, some classes have a dependency with even more dependencies, so it can take quite a while before it is able to respond to the symbols request.

You can see what the server is doing under "Output > UnrealScript" to confirm.

**Comment by EliotVU** [comment] 2023-01-30 23:39
I have two solutions for this that may make this more responsive:

1. Respond as soon as the document has sufficient data to feedback the symbols data.
2. As request, re-parse the entire document and just collect the symbols from the AST, bypassing the indexation of the document as we don't need any semantics here. This however is a bit wasteful :)

**Comment by EliotVU** [comment] 2023-01-30 23:41
> And a little post scriptum: seems like extension parses the document for symbols on each file switch / reopen. Maybe change it, so it triggers only on file modification?

This was done by design to ensure that the server is working the correct up-to-date document, for instance if you open a document and make some unsaved changes, and proceed to close this document, the server will re-process the document without any of the unsaved changes.

Surely this can be optimized, but it is not crucial as it has almost no impact on performance.

**Comment by Shtoyan** [comment] 2023-01-31 09:21
What comes to my mind at first - cache everything in the workspace? Most of the files, especially the game source code that you make mods for, never change. So you can just check the md5-file date and use the cached dependency and symbol tree. It will speed up the startup and new file opening significantly.

But honestly, I don't know how it's done and what's the best practice / the easiest way to do it in VSCode, so up to you, I guess.

**Closed** 2023-02-08 17:29 UTC
Labels: enhancement

**Comment by EliotVU** [comment] 2023-02-08 17:33
> 

Yeah, but this is out of scope for now, as the current approach may still be changed drastically, it would be a lot of work to keep a persisted cache compatible.

I solved this by waiting for the document to be indexed before the server sends a result of symbols. This fixes the issue where a list of symbols never gets retrieved. 

However this may still take (seconds) if the server is indexing multiple documents, this can definitely be improved on later, by responding right before indexing as we don't need the all the info that gets indexed.symbols to be indexed.

**Comment by Shtoyan** [comment] 2023-02-08 18:18
> This fixes the issue where a list of symbols never gets retrieved.

This is fine too, I'm used to wait a little bit for indexing. Thanks!
