### ISSUE TITLE
[Bug]: [v0.7.1] highlight source code as comment by mistake

### ISSUE THREAD

**Issue by zb2023zb** [EliotVU/UnrealScript-Language-Service#185] opened 2023-10-18 05:03 UTC
### Describe the bug

Please see the attchment.
[fw4.txt](https://github.com/EliotVU/UnrealScript-Language-Service/files/12984765/fw4.txt)

### Screenshots

![image](https://github.com/EliotVU/UnrealScript-Language-Service/assets/148300537/10867ad3-4a89-435c-99d6-44b219178b5b)

**Comment by Shtoyan** [comment] 2023-10-18 08:37
Duplicate of #183.

Ok, even if this is an invalid issue, you guys, seems like really need a help :d - that's not a bug, you are missing a closing `*/`.

**Closed** 2023-10-18 10:36 UTC
Labels: invalid

**Comment by zb2023zb** [comment] 2023-10-23 02:28
> Duplicate of #183.
> 
> Ok, even if this is an invalid issue, you guys, seems like really need a help :d - that's not a bug, you are missing a closing `*/`.

I don't think so, '/*' in '/*.nft'  doesn't mean to comment, the code can be treated as following:
```
`/usr/share/nftables.d/${position}${chain}/*.nft`
```
The whole statement is a regular expression.

**Comment by Shtoyan** [comment] 2023-10-23 10:37
The correct and best way of handling this could be:

> Hi, sorry for my incorrect (unrelated) issue. Anyhow i was able to google "javascript escape characters" (in 5 days) after i realized i gave no context to my first message.

**Comment by zb2023zb** [comment] 2023-10-24 00:28
Hi there,

Is this a bug? if so, can you fix it ? 

thanks a lot~

**Comment by zb2023zb** [comment] 2023-10-27 05:03
Hi there,

Is this a bug? if so, can you fix it ?

Thanks a lot~
