### ISSUE TITLE
[Bug]: Can't find .uc files in the same folder

### ISSUE THREAD

**Issue by humam2104** [EliotVU/UnrealScript-Language-Service#178] opened 2023-05-30 01:00 UTC
### Can't find .uc files next to the opened file
The program can't detect the files next to the .uc file I'm using (I'm currently modding killing floor 2). And all the classes should be right next to each other, but the program throws an error anyways. I won't be using this program for building anything, because there's a compiler for that.
The point is, the program doesn't realize that these files are next to it. I'm guessing that's because there's a "classes" folder.

### Screenshots

![image](https://github.com/EliotVU/UnrealScript-Language-Service/assets/41898465/f8bb580d-196f-413a-9649-dc5fcd6b911a)

**Comment by EliotVU** [comment] 2023-05-30 16:21
Are those diagnostics occurring in the defaultproperties code block? If so, there's currently a bug where it will not lookup the file for class types that are referenced within a defaultproperties block.

Nonetheless, you can enable "Index all documents" as a work around, or manually re-open the .uc documents that have not been found.

**Comment by humam2104** [comment] 2023-05-30 17:07
The files are referenced in a function, and not in defaultproperties.
![image](https://github.com/EliotVU/UnrealScript-Language-Service/assets/41898465/544be982-796d-45eb-8b8f-04ca5699e673)

**Comment by EliotVU** [comment] 2024-07-23 16:32
Closing this, the remaining errors are caused by issues with the macro preprocessor see #10

**Closed as not planned by EliotVU** 2024-07-23 16:32 UTC
Labels: bug, help wanted
